exercise 10

diff --git a/.github/workflows/09-exercise.yaml b/.github/workflows/09-exercise.yaml
--- a/.github/workflows/09-exercise.yaml
+++ b/.github/workflows/09-exercise.yaml
@@ -1,3 +1,24 @@
 name: 09-exercise
-on:
+on: workflow_dispatch
 jobs:
+  echo1:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failing Step
+        run: |
+          exit 1
+      - name: I will be skipped
+        run: |
+          echo "I will print if previous steps suceeded"
+      - name: I will execute
+        if: ${{ failure() }}
+        run: |
+          echo "I will print if any previous steps failed
+      - name: I will execute
+        if: ${{ !cancelled() }}
+        run: |
+          echo "I will always print, except when the workflow is cancelled"
+      - name: I will execute when cancelled
+        if: ${{ cancelled()}}
+        run: |
+          echo "I will print if the workflow is cancelled"
